name: fl_score_bar
description: Flutter custom ScoreBar that provides 2 types of ScoreBar, FlScoreBar and IconScoreBar, both can be immutable/mutable.
version: 0.2.3
homepage: https://github.com/mobinsafaeian/FlScoreBar.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0