name: fl_score_bar
description: Flutter custom ScoreBar that provides 2 states, mutable and immutable for submitting and showing the content score.
version: 0.0.1
homepage: https://github.com/mobinsafaeian/FlScoreBar.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0